name: Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build --if-present
      
    - name: Run tests
      run: npm test --if-present
      
    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./build
        
    - name: Upload distribution files
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-results
      if: always()